c++ -o255 255.cpp
c++ -oa a.cpp
c++ -oananas ananas.cpp
c++ -o binary_i binary_i.cpp
c++ -obinary_s binary_s.cpp
c++ -obity bity.cpp
c++ -obit_operations bit_operations.cpp
c++ -obm bm.cpp
c++ -obreadth breadth.cpp
c++ -obubble bubble.cpp
c++ -ocomplex complex.cpp
c++ -odepthf depthf.cpp
c++ -odobor dobor.cpp
c++ -odyn dyn.cpp
c++ -odziedzic dziedzic.cpp
c++ -oerastot erastot.cpp
c++ -ofib_dyn fib-dyn.cpp
c++ -ofloyd floyd.cpp
c++ -ofloyd2 floyd2.cpp
c++ -ogauss gauss.cpp
c++ -ogreedy greedy.cpp
c++ -ohanoi hanoi.cpp
c++ -ohanoi2 hanoi2.cpp
c++ -ohanoi_it hanoi_it.cpp
c++ -ohash hash.cpp
c++ -oheap heap.cpp
c++ -oheapsort heapsort.cpp
c++ -ohorner horner.cpp
c++ -oinsert insert.cpp
c++ -ointerpol interpol.cpp
c++ -okmp kmp.cpp
c++ -okolejka kolejka.cpp
c++ -okompoz kompoz.cpp
c++ -olinearo linear.cpp
c++ -olist_tab list_tab.cpp
c++ -olista lista.cpp
c++ -olista2 lista2.cpp
c++ -omerge merge.cpp
c++ -omin_max min-max.cpp
c++ -onewtonf newton.cpp
c++ -onwd nwd.cpp
c++ -ooblicz oblicz.cpp
c++ -oodwrot2 odwrot2.cpp
c++ -oodwrotna odwrotna.cpp
c++ -opalindro palindro.cpp
c++ -opliki pliki.cpp
c++ -opochodna pochodna.cpp
c++ -opost_2 post_2.cpp
c++ -opot pot.cpp
c++ -oqsort qsort.cpp
c++ -oqsort2 qsort2.cpp
c++ -orek1 rek1.cpp
c++ -orek2 rek2.cpp
c++ -orek2_ite rek2_ite.cpp
c++ -orek3 rek3.cpp
c++ -orek4 rek4.cpp
c++ -orek5 rek5.cpp
c++ -orev_tab rev_tab.cpp
c++ -ork rk.cpp
c++ -oroute route.cpp
c++ -oset set.cpp
c++ -oshaker  shaker.cpp
c++ -osimpson simpson.cpp
c++ -ostd std.cpp
c++ -osterta sterta.cpp
c++ -ostos stos.cpp
c++ -ostosfloa stosfloa.cpp
c++ -oszukaj szukaj.cpp
c++ -otictac tictac.cpp
c++ -otransl transl.cpp
c++ -otxt-1 txt-1.cpp
c++ -ouss uss.cpp
c++ -owarshall warshall.cpp
c++ -owartf wartf.cpp
c++ -owielom wielom.cpp
c++ -owielom2 wielom2.cpp
c++ -owsk_fun wsk_fun.cpp
c++ -owyrazen wyrazen.cpp
c++ -oxor xor.cpp
c++ -oznaki znaki.cpp

